controllers:
    resource: ../../src/Http/Controller/
    type: annotation

controllers_api:
    resource: ../../src/Http/Api/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
